# Generated by Django 4.0.4 on 2022-08-26 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.FloatField(default=0.0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='VatCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('value', models.FloatField(default=0.0, max_length=11)),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='src.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=50, null=True)),
                ('net_amount', models.FloatField(default=0.0, max_length=11)),
                ('gross_amount', models.FloatField(default=0.0, max_length=11)),
                ('discount', models.FloatField(default=0.0, max_length=11)),
                ('vat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.vatcode')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit_note', 'Credit Note'), ('quote', 'Quote')], max_length=50)),
                ('net_amount', models.FloatField(default=0.0, max_length=11)),
                ('gross_amount', models.FloatField(default=0.0, max_length=11)),
                ('tax_amount', models.FloatField(default=0.0, max_length=11)),
                ('taxes_total', models.FloatField(default=0.0, max_length=11)),
                ('contributes_total', models.FloatField(default=0.0, max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_id', to='src.entity')),
                ('items', models.ManyToManyField(related_name='items', to='src.documentitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_organization', to='src.organization')),
                ('payments', models.ManyToManyField(related_name='payments', to='src.documentpayment')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
