# Generated by Django 4.0.4 on 2022-08-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Entity',
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
    ]
