# Generated by Django 4.0.4 on 2022-08-26 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_entity_organization_alter_entity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcode',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.organization'),
        ),
    ]
