# Generated by Django 4.0.4 on 2022-08-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_vatcode_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
