# Generated by Django 4.0.4 on 2022-08-26 00:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_document_date_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('iban', models.CharField(default=None, max_length=100, null=True)),
                ('accountholder', models.CharField(default=None, max_length=100, null=True)),
                ('subject', models.CharField(default=None, max_length=100, null=True)),
                ('bank', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='payment_method',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.documentpayment'),
        ),
    ]
